# Generated by Django 5.1.5 on 2025-04-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0002_rename_userprofile_userdashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdashboard',
            name='bio',
        ),
    ]
