# Generated by Django 5.1.5 on 2025-04-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0003_remove_userdashboard_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdashboard',
            name='phone',
        ),
    ]
