# Generated by Django 5.1.5 on 2025-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
