# Generated by Django 5.1.5 on 2025-04-06 15:33

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0007_remove_userdashboard_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
